version: '3'
services:
  postgres:
    image: postgres:11.2
    ports:
      - '5434:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: form3-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
